### ISSUE TITLE
[18.0][queue_job]: AttributeError: module 'odoo.api' has no attribute 'private'

### ISSUE THREAD

**Issue by p0-k9** [OCA/queue#806]
## Module
The module `queue_job`  has a bug.

## Describe the bug

<img width="1823" height="607" alt="Image" src="https://github.com/user-attachments/assets/b464580f-b55d-4f8f-b4b9-2c5f0bda7b29" />

## To Reproduce
**Affected versions**:

1.
2.
3.

**Expected behavior**

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by p0-k9** [comment]
@amh-mw 
When running branch 18.0 I get the error as described, do you have any instructions to help me fix it please let me know.
Thank you very much

**Comment by amh-mw** [comment]
Reading your logs above it looks like you are running an older Odoo 18 with source code dated 2025/02/07 and the api.private decorator was introduced by https://github.com/odoo/odoo/commit/c7efed2bcd827b28296d1b49ab42481782f483bd on 2025/02/28, so a newer version of 18.0 should set things right.

**Comment by simahawk** [comment]
same as https://github.com/OCA/queue/issues/803
